{% set name = "avro-python3" %}
{% set version = "1.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/avro-python3-{{ version }}.tar.gz
  sha256: 3b63f24e6b04368c3e4a6f923f484be0230d821aad65ac36108edbff29e9aaab

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - avro
    - isort
    - pycodestyle
  run:
    - python >={{ python_min }}

test:
  imports:
    - avro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://avro.apache.org/
  summary: Avro is a serialization and RPC framework.
  license: Apache-2.0
  license_file: avro/LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
